# Generated by Django 5.0.1 on 2024-01-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Passs', models.CharField(max_length=100)),
                ('Cpass', models.CharField(max_length=100)),
            ],
        ),
    ]
